//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Gsafety.PTMS.ServiceReference.OrderClientService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderClient", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx))]
    public partial class OrderClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AddressField;
        
        private System.DateTime BeginTimeField;
        
        private string ContactField;
        
        private int DeviceCountField;
        
        private string EmailField;
        
        private System.DateTime EndTimeField;
        
        private string IDField;
        
        private string MobileField;
        
        private string NameField;
        
        private string PhoneField;
        
        private Gsafety.PTMS.ServiceReference.OrderClientService.StatusEnum StatusField;
        
        private Gsafety.PTMS.ServiceReference.OrderClientService.TansferModeEnum TansferModeField;
        
        private int UserCountField;
        
        private short _platformversionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceCount {
            get {
                return this.DeviceCountField;
            }
            set {
                if ((this.DeviceCountField.Equals(value) != true)) {
                    this.DeviceCountField = value;
                    this.RaisePropertyChanged("DeviceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gsafety.PTMS.ServiceReference.OrderClientService.StatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gsafety.PTMS.ServiceReference.OrderClientService.TansferModeEnum TansferMode {
            get {
                return this.TansferModeField;
            }
            set {
                if ((this.TansferModeField.Equals(value) != true)) {
                    this.TansferModeField = value;
                    this.RaisePropertyChanged("TansferMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCount {
            get {
                return this.UserCountField;
            }
            set {
                if ((this.UserCountField.Equals(value) != true)) {
                    this.UserCountField = value;
                    this.RaisePropertyChanged("UserCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short _platformversion {
            get {
                return this._platformversionField;
            }
            set {
                if ((this._platformversionField.Equals(value) != true)) {
                    this._platformversionField = value;
                    this.RaisePropertyChanged("_platformversion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderClientEx", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    public partial class OrderClientEx : Gsafety.PTMS.ServiceReference.OrderClientService.OrderClient {
        
        private int ActualDeviceCountField;
        
        private int ActualUserCountField;
        
        private int RowField;
        
        private string StatusStrField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualDeviceCount {
            get {
                return this.ActualDeviceCountField;
            }
            set {
                if ((this.ActualDeviceCountField.Equals(value) != true)) {
                    this.ActualDeviceCountField = value;
                    this.RaisePropertyChanged("ActualDeviceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualUserCount {
            get {
                return this.ActualUserCountField;
            }
            set {
                if ((this.ActualUserCountField.Equals(value) != true)) {
                    this.ActualUserCountField = value;
                    this.RaisePropertyChanged("ActualUserCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusStr {
            get {
                return this.StatusStrField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusStrField, value) != true)) {
                    this.StatusStrField = value;
                    this.RaisePropertyChanged("StatusStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusEnum", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    public enum StatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stop = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TansferModeEnum", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    public enum TansferModeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTransfer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DirectTransfer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JudgeTransfer = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogManager", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    public partial class LogManager : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ClientIDField;
        
        private string ClientNameField;
        
        private string ContentField;
        
        private System.DateTime CreateTimeField;
        
        private string IDField;
        
        private string ManagerField;
        
        private string ManagerIDField;
        
        private string UserDeptField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerID {
            get {
                return this.ManagerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerIDField, value) != true)) {
                    this.ManagerIDField = value;
                    this.RaisePropertyChanged("ManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDept {
            get {
                return this.UserDeptField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDeptField, value) != true)) {
                    this.UserDeptField = value;
                    this.RaisePropertyChanged("UserDept");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMessageOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class SingleMessageOfboolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private bool ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel))]
    public partial class PagingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderClientManagerQueryModel", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.BaseInformation.Contract.Mod" +
        "els")]
    public partial class OrderClientManagerQueryModel : Gsafety.PTMS.ServiceReference.OrderClientService.PagingInfo {
        
        private string NameField;
        
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiMessageOfOrderClientExi7Zg_POJ5", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class MultiMessageOfOrderClientExi7Zg_POJ5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx> ResultField;
        
        private int TotalRecordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecord {
            get {
                return this.TotalRecordField;
            }
            set {
                if ((this.TotalRecordField.Equals(value) != true)) {
                    this.TotalRecordField = value;
                    this.RaisePropertyChanged("TotalRecord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMessageOfOrderClienti7Zg_POJ5", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class SingleMessageOfOrderClienti7Zg_POJ5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private Gsafety.PTMS.ServiceReference.OrderClientService.OrderClient ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gsafety.PTMS.ServiceReference.OrderClientService.OrderClient Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderClientService.IOrderClientService")]
    public interface IOrderClientService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/InsertOrderClient", ReplyAction="http://tempuri.org/IOrderClientService/InsertOrderClientResponse")]
        System.IAsyncResult BeginInsertOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndInsertOrderClient(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/UpdateOrderClient", ReplyAction="http://tempuri.org/IOrderClientService/UpdateOrderClientResponse")]
        System.IAsyncResult BeginUpdateOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndUpdateOrderClient(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/GetOrderClientExList", ReplyAction="http://tempuri.org/IOrderClientService/GetOrderClientExListResponse")]
        System.IAsyncResult BeginGetOrderClientExList(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 EndGetOrderClientExList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/ResetPassword", ReplyAction="http://tempuri.org/IOrderClientService/ResetPasswordResponse")]
        System.IAsyncResult BeginResetPassword(string orderClientID, string newPassword, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndResetPassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/SetOrderClientStatus", ReplyAction="http://tempuri.org/IOrderClientService/SetOrderClientStatusResponse")]
        System.IAsyncResult BeginSetOrderClientStatus(string orderClientID, bool enable, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndSetOrderClientStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderClientService/GetOrderClient", ReplyAction="http://tempuri.org/IOrderClientService/GetOrderClientResponse")]
        System.IAsyncResult BeginGetOrderClient(string ID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 EndGetOrderClient(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderClientServiceChannel : Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertOrderClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertOrderClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateOrderClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateOrderClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderClientExListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderClientExListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetOrderClientStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetOrderClientStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderClientServiceClient : System.ServiceModel.ClientBase<Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService>, Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService {
        
        private BeginOperationDelegate onBeginInsertOrderClientDelegate;
        
        private EndOperationDelegate onEndInsertOrderClientDelegate;
        
        private System.Threading.SendOrPostCallback onInsertOrderClientCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateOrderClientDelegate;
        
        private EndOperationDelegate onEndUpdateOrderClientDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateOrderClientCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrderClientExListDelegate;
        
        private EndOperationDelegate onEndGetOrderClientExListDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderClientExListCompletedDelegate;
        
        private BeginOperationDelegate onBeginResetPasswordDelegate;
        
        private EndOperationDelegate onEndResetPasswordDelegate;
        
        private System.Threading.SendOrPostCallback onResetPasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetOrderClientStatusDelegate;
        
        private EndOperationDelegate onEndSetOrderClientStatusDelegate;
        
        private System.Threading.SendOrPostCallback onSetOrderClientStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrderClientDelegate;
        
        private EndOperationDelegate onEndGetOrderClientDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderClientCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OrderClientServiceClient() {
        }
        
        public OrderClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<InsertOrderClientCompletedEventArgs> InsertOrderClientCompleted;
        
        public event System.EventHandler<UpdateOrderClientCompletedEventArgs> UpdateOrderClientCompleted;
        
        public event System.EventHandler<GetOrderClientExListCompletedEventArgs> GetOrderClientExListCompleted;
        
        public event System.EventHandler<ResetPasswordCompletedEventArgs> ResetPasswordCompleted;
        
        public event System.EventHandler<SetOrderClientStatusCompletedEventArgs> SetOrderClientStatusCompleted;
        
        public event System.EventHandler<GetOrderClientCompletedEventArgs> GetOrderClientCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginInsertOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertOrderClient(model, log, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndInsertOrderClient(System.IAsyncResult result) {
            return base.Channel.EndInsertOrderClient(result);
        }
        
        private System.IAsyncResult OnBeginInsertOrderClient(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model = ((Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx)(inValues[0]));
            Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log = ((Gsafety.PTMS.ServiceReference.OrderClientService.LogManager)(inValues[1]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginInsertOrderClient(model, log, callback, asyncState);
        }
        
        private object[] OnEndInsertOrderClient(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndInsertOrderClient(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertOrderClientCompleted(object state) {
            if ((this.InsertOrderClientCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertOrderClientCompleted(this, new InsertOrderClientCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertOrderClientAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log) {
            this.InsertOrderClientAsync(model, log, null);
        }
        
        public void InsertOrderClientAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, object userState) {
            if ((this.onBeginInsertOrderClientDelegate == null)) {
                this.onBeginInsertOrderClientDelegate = new BeginOperationDelegate(this.OnBeginInsertOrderClient);
            }
            if ((this.onEndInsertOrderClientDelegate == null)) {
                this.onEndInsertOrderClientDelegate = new EndOperationDelegate(this.OnEndInsertOrderClient);
            }
            if ((this.onInsertOrderClientCompletedDelegate == null)) {
                this.onInsertOrderClientCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertOrderClientCompleted);
            }
            base.InvokeAsync(this.onBeginInsertOrderClientDelegate, new object[] {
                        model,
                        log}, this.onEndInsertOrderClientDelegate, this.onInsertOrderClientCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginUpdateOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateOrderClient(model, log, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndUpdateOrderClient(System.IAsyncResult result) {
            return base.Channel.EndUpdateOrderClient(result);
        }
        
        private System.IAsyncResult OnBeginUpdateOrderClient(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model = ((Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx)(inValues[0]));
            Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log = ((Gsafety.PTMS.ServiceReference.OrderClientService.LogManager)(inValues[1]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginUpdateOrderClient(model, log, callback, asyncState);
        }
        
        private object[] OnEndUpdateOrderClient(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndUpdateOrderClient(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateOrderClientCompleted(object state) {
            if ((this.UpdateOrderClientCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateOrderClientCompleted(this, new UpdateOrderClientCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateOrderClientAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log) {
            this.UpdateOrderClientAsync(model, log, null);
        }
        
        public void UpdateOrderClientAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, object userState) {
            if ((this.onBeginUpdateOrderClientDelegate == null)) {
                this.onBeginUpdateOrderClientDelegate = new BeginOperationDelegate(this.OnBeginUpdateOrderClient);
            }
            if ((this.onEndUpdateOrderClientDelegate == null)) {
                this.onEndUpdateOrderClientDelegate = new EndOperationDelegate(this.OnEndUpdateOrderClient);
            }
            if ((this.onUpdateOrderClientCompletedDelegate == null)) {
                this.onUpdateOrderClientCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateOrderClientCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateOrderClientDelegate, new object[] {
                        model,
                        log}, this.onEndUpdateOrderClientDelegate, this.onUpdateOrderClientCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginGetOrderClientExList(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrderClientExList(obj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndGetOrderClientExList(System.IAsyncResult result) {
            return base.Channel.EndGetOrderClientExList(result);
        }
        
        private System.IAsyncResult OnBeginGetOrderClientExList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj = ((Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginGetOrderClientExList(obj, callback, asyncState);
        }
        
        private object[] OnEndGetOrderClientExList(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndGetOrderClientExList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderClientExListCompleted(object state) {
            if ((this.GetOrderClientExListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderClientExListCompleted(this, new GetOrderClientExListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderClientExListAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj) {
            this.GetOrderClientExListAsync(obj, null);
        }
        
        public void GetOrderClientExListAsync(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj, object userState) {
            if ((this.onBeginGetOrderClientExListDelegate == null)) {
                this.onBeginGetOrderClientExListDelegate = new BeginOperationDelegate(this.OnBeginGetOrderClientExList);
            }
            if ((this.onEndGetOrderClientExListDelegate == null)) {
                this.onEndGetOrderClientExListDelegate = new EndOperationDelegate(this.OnEndGetOrderClientExList);
            }
            if ((this.onGetOrderClientExListCompletedDelegate == null)) {
                this.onGetOrderClientExListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderClientExListCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderClientExListDelegate, new object[] {
                        obj}, this.onEndGetOrderClientExListDelegate, this.onGetOrderClientExListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginResetPassword(string orderClientID, string newPassword, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResetPassword(orderClientID, newPassword, log, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndResetPassword(System.IAsyncResult result) {
            return base.Channel.EndResetPassword(result);
        }
        
        private System.IAsyncResult OnBeginResetPassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string orderClientID = ((string)(inValues[0]));
            string newPassword = ((string)(inValues[1]));
            Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log = ((Gsafety.PTMS.ServiceReference.OrderClientService.LogManager)(inValues[2]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginResetPassword(orderClientID, newPassword, log, callback, asyncState);
        }
        
        private object[] OnEndResetPassword(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndResetPassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResetPasswordCompleted(object state) {
            if ((this.ResetPasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResetPasswordCompleted(this, new ResetPasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResetPasswordAsync(string orderClientID, string newPassword, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log) {
            this.ResetPasswordAsync(orderClientID, newPassword, log, null);
        }
        
        public void ResetPasswordAsync(string orderClientID, string newPassword, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, object userState) {
            if ((this.onBeginResetPasswordDelegate == null)) {
                this.onBeginResetPasswordDelegate = new BeginOperationDelegate(this.OnBeginResetPassword);
            }
            if ((this.onEndResetPasswordDelegate == null)) {
                this.onEndResetPasswordDelegate = new EndOperationDelegate(this.OnEndResetPassword);
            }
            if ((this.onResetPasswordCompletedDelegate == null)) {
                this.onResetPasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResetPasswordCompleted);
            }
            base.InvokeAsync(this.onBeginResetPasswordDelegate, new object[] {
                        orderClientID,
                        newPassword,
                        log}, this.onEndResetPasswordDelegate, this.onResetPasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginSetOrderClientStatus(string orderClientID, bool enable, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetOrderClientStatus(orderClientID, enable, log, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndSetOrderClientStatus(System.IAsyncResult result) {
            return base.Channel.EndSetOrderClientStatus(result);
        }
        
        private System.IAsyncResult OnBeginSetOrderClientStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string orderClientID = ((string)(inValues[0]));
            bool enable = ((bool)(inValues[1]));
            Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log = ((Gsafety.PTMS.ServiceReference.OrderClientService.LogManager)(inValues[2]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginSetOrderClientStatus(orderClientID, enable, log, callback, asyncState);
        }
        
        private object[] OnEndSetOrderClientStatus(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndSetOrderClientStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetOrderClientStatusCompleted(object state) {
            if ((this.SetOrderClientStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetOrderClientStatusCompleted(this, new SetOrderClientStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetOrderClientStatusAsync(string orderClientID, bool enable, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log) {
            this.SetOrderClientStatusAsync(orderClientID, enable, log, null);
        }
        
        public void SetOrderClientStatusAsync(string orderClientID, bool enable, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, object userState) {
            if ((this.onBeginSetOrderClientStatusDelegate == null)) {
                this.onBeginSetOrderClientStatusDelegate = new BeginOperationDelegate(this.OnBeginSetOrderClientStatus);
            }
            if ((this.onEndSetOrderClientStatusDelegate == null)) {
                this.onEndSetOrderClientStatusDelegate = new EndOperationDelegate(this.OnEndSetOrderClientStatus);
            }
            if ((this.onSetOrderClientStatusCompletedDelegate == null)) {
                this.onSetOrderClientStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetOrderClientStatusCompleted);
            }
            base.InvokeAsync(this.onBeginSetOrderClientStatusDelegate, new object[] {
                        orderClientID,
                        enable,
                        log}, this.onEndSetOrderClientStatusDelegate, this.onSetOrderClientStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.BeginGetOrderClient(string ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrderClient(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService.EndGetOrderClient(System.IAsyncResult result) {
            return base.Channel.EndGetOrderClient(result);
        }
        
        private System.IAsyncResult OnBeginGetOrderClient(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID = ((string)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).BeginGetOrderClient(ID, callback, asyncState);
        }
        
        private object[] OnEndGetOrderClient(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService)(this)).EndGetOrderClient(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderClientCompleted(object state) {
            if ((this.GetOrderClientCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderClientCompleted(this, new GetOrderClientCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderClientAsync(string ID) {
            this.GetOrderClientAsync(ID, null);
        }
        
        public void GetOrderClientAsync(string ID, object userState) {
            if ((this.onBeginGetOrderClientDelegate == null)) {
                this.onBeginGetOrderClientDelegate = new BeginOperationDelegate(this.OnBeginGetOrderClient);
            }
            if ((this.onEndGetOrderClientDelegate == null)) {
                this.onEndGetOrderClientDelegate = new EndOperationDelegate(this.OnEndGetOrderClient);
            }
            if ((this.onGetOrderClientCompletedDelegate == null)) {
                this.onGetOrderClientCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderClientCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderClientDelegate, new object[] {
                        ID}, this.onEndGetOrderClientDelegate, this.onGetOrderClientCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService CreateChannel() {
            return new OrderClientServiceClientChannel(this);
        }
        
        private class OrderClientServiceClientChannel : ChannelBase<Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService>, Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService {
            
            public OrderClientServiceClientChannel(System.ServiceModel.ClientBase<Gsafety.PTMS.ServiceReference.OrderClientService.IOrderClientService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInsertOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = model;
                _args[1] = log;
                System.IAsyncResult _result = base.BeginInvoke("InsertOrderClient", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndInsertOrderClient(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(base.EndInvoke("InsertOrderClient", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateOrderClient(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientEx model, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = model;
                _args[1] = log;
                System.IAsyncResult _result = base.BeginInvoke("UpdateOrderClient", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndUpdateOrderClient(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(base.EndInvoke("UpdateOrderClient", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetOrderClientExList(Gsafety.PTMS.ServiceReference.OrderClientService.OrderClientManagerQueryModel obj, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = obj;
                System.IAsyncResult _result = base.BeginInvoke("GetOrderClientExList", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 EndGetOrderClientExList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.MultiMessageOfOrderClientExi7Zg_POJ5)(base.EndInvoke("GetOrderClientExList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginResetPassword(string orderClientID, string newPassword, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = orderClientID;
                _args[1] = newPassword;
                _args[2] = log;
                System.IAsyncResult _result = base.BeginInvoke("ResetPassword", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndResetPassword(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(base.EndInvoke("ResetPassword", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetOrderClientStatus(string orderClientID, bool enable, Gsafety.PTMS.ServiceReference.OrderClientService.LogManager log, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = orderClientID;
                _args[1] = enable;
                _args[2] = log;
                System.IAsyncResult _result = base.BeginInvoke("SetOrderClientStatus", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean EndSetOrderClientStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfboolean)(base.EndInvoke("SetOrderClientStatus", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetOrderClient(string ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("GetOrderClient", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 EndGetOrderClient(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.OrderClientService.SingleMessageOfOrderClienti7Zg_POJ5)(base.EndInvoke("GetOrderClient", _args, result)));
                return _result;
            }
        }
    }
}
