//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Gsafety.PTMS.ServiceReference.DevGpsService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DevGps", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Data")]
    public partial class DevGps : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ClientIdField;
        
        private System.DateTime CreateTimeField;
        
        private string CreatorField;
        
        private string DisplayInstallStatusField;
        
        private string DistrictCodeField;
        
        private string GpsSimField;
        
        private string GpsSnField;
        
        private string GpsUidField;
        
        private string IDField;
        
        private Gsafety.PTMS.ServiceReference.DevGpsService.InstallStatusType InstallStatusField;
        
        private decimal StatusField;
        
        private decimal ValidField;
        
        private string VehicleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayInstallStatus {
            get {
                return this.DisplayInstallStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayInstallStatusField, value) != true)) {
                    this.DisplayInstallStatusField = value;
                    this.RaisePropertyChanged("DisplayInstallStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictCode {
            get {
                return this.DistrictCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictCodeField, value) != true)) {
                    this.DistrictCodeField = value;
                    this.RaisePropertyChanged("DistrictCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GpsSim {
            get {
                return this.GpsSimField;
            }
            set {
                if ((object.ReferenceEquals(this.GpsSimField, value) != true)) {
                    this.GpsSimField = value;
                    this.RaisePropertyChanged("GpsSim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GpsSn {
            get {
                return this.GpsSnField;
            }
            set {
                if ((object.ReferenceEquals(this.GpsSnField, value) != true)) {
                    this.GpsSnField = value;
                    this.RaisePropertyChanged("GpsSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GpsUid {
            get {
                return this.GpsUidField;
            }
            set {
                if ((object.ReferenceEquals(this.GpsUidField, value) != true)) {
                    this.GpsUidField = value;
                    this.RaisePropertyChanged("GpsUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gsafety.PTMS.ServiceReference.DevGpsService.InstallStatusType InstallStatus {
            get {
                return this.InstallStatusField;
            }
            set {
                if ((this.InstallStatusField.Equals(value) != true)) {
                    this.InstallStatusField = value;
                    this.RaisePropertyChanged("InstallStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valid {
            get {
                return this.ValidField;
            }
            set {
                if ((this.ValidField.Equals(value) != true)) {
                    this.ValidField = value;
                    this.RaisePropertyChanged("Valid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleIDField, value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstallStatusType", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Common.Enum")]
    public enum InstallStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnInstall = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Installing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Installed = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMessageOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class SingleMessageOfboolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private bool ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMessageOfDevGpsi7Zg_POJ5", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class SingleMessageOfDevGpsi7Zg_POJ5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private Gsafety.PTMS.ServiceReference.DevGpsService.DevGps ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gsafety.PTMS.ServiceReference.DevGpsService.DevGps Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class PagingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiMessageOfDevGpsi7Zg_POJ5", Namespace="http://schemas.datacontract.org/2004/07/Gsafety.PTMS.Base.Contract.Data")]
    public partial class MultiMessageOfDevGpsi7Zg_POJ5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorDetailMsgField;
        
        private string ErrorMsgField;
        
        private System.Exception ExceptionMessageField;
        
        private bool IsSuccessField;
        
        private System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> ResultField;
        
        private int TotalRecordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetailMsg {
            get {
                return this.ErrorDetailMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailMsgField, value) != true)) {
                    this.ErrorDetailMsgField = value;
                    this.RaisePropertyChanged("ErrorDetailMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecord {
            get {
                return this.TotalRecordField;
            }
            set {
                if ((this.TotalRecordField.Equals(value) != true)) {
                    this.TotalRecordField = value;
                    this.RaisePropertyChanged("TotalRecord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevGpsService.IDevGpsService")]
    public interface IDevGpsService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/InsertDevGps", ReplyAction="http://tempuri.org/IDevGpsService/InsertDevGpsResponse")]
        System.IAsyncResult BeginInsertDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndInsertDevGps(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/UpdateDevGps", ReplyAction="http://tempuri.org/IDevGpsService/UpdateDevGpsResponse")]
        System.IAsyncResult BeginUpdateDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndUpdateDevGps(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/DeleteDevGpsByID", ReplyAction="http://tempuri.org/IDevGpsService/DeleteDevGpsByIDResponse")]
        System.IAsyncResult BeginDeleteDevGpsByID(string ID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndDeleteDevGpsByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/GetDevGps", ReplyAction="http://tempuri.org/IDevGpsService/GetDevGpsResponse")]
        System.IAsyncResult BeginGetDevGps(string ID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 EndGetDevGps(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/GetDevGpsBySN", ReplyAction="http://tempuri.org/IDevGpsService/GetDevGpsBySNResponse")]
        System.IAsyncResult BeginGetDevGpsBySN(string ID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 EndGetDevGpsBySN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/GetDevGpsList", ReplyAction="http://tempuri.org/IDevGpsService/GetDevGpsListResponse")]
        System.IAsyncResult BeginGetDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndGetDevGpsList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/GetByNameDevGpsList", ReplyAction="http://tempuri.org/IDevGpsService/GetByNameDevGpsListResponse")]
        System.IAsyncResult BeginGetByNameDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, string name, string vehicleID, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndGetByNameDevGpsList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/BatchAddDevGps", ReplyAction="http://tempuri.org/IDevGpsService/BatchAddDevGpsResponse")]
        System.IAsyncResult BeginBatchAddDevGps(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndBatchAddDevGps(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDevGpsService/CheckDevGpsExist", ReplyAction="http://tempuri.org/IDevGpsService/CheckDevGpsExistResponse")]
        System.IAsyncResult BeginCheckDevGpsExist(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState);
        
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndCheckDevGpsExist(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDevGpsServiceChannel : Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDevGpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertDevGpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateDevGpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateDevGpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteDevGpsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteDevGpsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDevGpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDevGpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDevGpsBySNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDevGpsBySNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDevGpsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDevGpsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByNameDevGpsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByNameDevGpsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchAddDevGpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BatchAddDevGpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckDevGpsExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckDevGpsExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevGpsServiceClient : System.ServiceModel.ClientBase<Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService>, Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService {
        
        private BeginOperationDelegate onBeginInsertDevGpsDelegate;
        
        private EndOperationDelegate onEndInsertDevGpsDelegate;
        
        private System.Threading.SendOrPostCallback onInsertDevGpsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDevGpsDelegate;
        
        private EndOperationDelegate onEndUpdateDevGpsDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateDevGpsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDevGpsByIDDelegate;
        
        private EndOperationDelegate onEndDeleteDevGpsByIDDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteDevGpsByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDevGpsDelegate;
        
        private EndOperationDelegate onEndGetDevGpsDelegate;
        
        private System.Threading.SendOrPostCallback onGetDevGpsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDevGpsBySNDelegate;
        
        private EndOperationDelegate onEndGetDevGpsBySNDelegate;
        
        private System.Threading.SendOrPostCallback onGetDevGpsBySNCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDevGpsListDelegate;
        
        private EndOperationDelegate onEndGetDevGpsListDelegate;
        
        private System.Threading.SendOrPostCallback onGetDevGpsListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByNameDevGpsListDelegate;
        
        private EndOperationDelegate onEndGetByNameDevGpsListDelegate;
        
        private System.Threading.SendOrPostCallback onGetByNameDevGpsListCompletedDelegate;
        
        private BeginOperationDelegate onBeginBatchAddDevGpsDelegate;
        
        private EndOperationDelegate onEndBatchAddDevGpsDelegate;
        
        private System.Threading.SendOrPostCallback onBatchAddDevGpsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckDevGpsExistDelegate;
        
        private EndOperationDelegate onEndCheckDevGpsExistDelegate;
        
        private System.Threading.SendOrPostCallback onCheckDevGpsExistCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DevGpsServiceClient() {
        }
        
        public DevGpsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevGpsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevGpsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevGpsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<InsertDevGpsCompletedEventArgs> InsertDevGpsCompleted;
        
        public event System.EventHandler<UpdateDevGpsCompletedEventArgs> UpdateDevGpsCompleted;
        
        public event System.EventHandler<DeleteDevGpsByIDCompletedEventArgs> DeleteDevGpsByIDCompleted;
        
        public event System.EventHandler<GetDevGpsCompletedEventArgs> GetDevGpsCompleted;
        
        public event System.EventHandler<GetDevGpsBySNCompletedEventArgs> GetDevGpsBySNCompleted;
        
        public event System.EventHandler<GetDevGpsListCompletedEventArgs> GetDevGpsListCompleted;
        
        public event System.EventHandler<GetByNameDevGpsListCompletedEventArgs> GetByNameDevGpsListCompleted;
        
        public event System.EventHandler<BatchAddDevGpsCompletedEventArgs> BatchAddDevGpsCompleted;
        
        public event System.EventHandler<CheckDevGpsExistCompletedEventArgs> CheckDevGpsExistCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginInsertDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertDevGps(model, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndInsertDevGps(System.IAsyncResult result) {
            return base.Channel.EndInsertDevGps(result);
        }
        
        private System.IAsyncResult OnBeginInsertDevGps(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model = ((Gsafety.PTMS.ServiceReference.DevGpsService.DevGps)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginInsertDevGps(model, callback, asyncState);
        }
        
        private object[] OnEndInsertDevGps(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndInsertDevGps(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertDevGpsCompleted(object state) {
            if ((this.InsertDevGpsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertDevGpsCompleted(this, new InsertDevGpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertDevGpsAsync(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model) {
            this.InsertDevGpsAsync(model, null);
        }
        
        public void InsertDevGpsAsync(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, object userState) {
            if ((this.onBeginInsertDevGpsDelegate == null)) {
                this.onBeginInsertDevGpsDelegate = new BeginOperationDelegate(this.OnBeginInsertDevGps);
            }
            if ((this.onEndInsertDevGpsDelegate == null)) {
                this.onEndInsertDevGpsDelegate = new EndOperationDelegate(this.OnEndInsertDevGps);
            }
            if ((this.onInsertDevGpsCompletedDelegate == null)) {
                this.onInsertDevGpsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertDevGpsCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDevGpsDelegate, new object[] {
                        model}, this.onEndInsertDevGpsDelegate, this.onInsertDevGpsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginUpdateDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateDevGps(model, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndUpdateDevGps(System.IAsyncResult result) {
            return base.Channel.EndUpdateDevGps(result);
        }
        
        private System.IAsyncResult OnBeginUpdateDevGps(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model = ((Gsafety.PTMS.ServiceReference.DevGpsService.DevGps)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginUpdateDevGps(model, callback, asyncState);
        }
        
        private object[] OnEndUpdateDevGps(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndUpdateDevGps(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateDevGpsCompleted(object state) {
            if ((this.UpdateDevGpsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateDevGpsCompleted(this, new UpdateDevGpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateDevGpsAsync(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model) {
            this.UpdateDevGpsAsync(model, null);
        }
        
        public void UpdateDevGpsAsync(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, object userState) {
            if ((this.onBeginUpdateDevGpsDelegate == null)) {
                this.onBeginUpdateDevGpsDelegate = new BeginOperationDelegate(this.OnBeginUpdateDevGps);
            }
            if ((this.onEndUpdateDevGpsDelegate == null)) {
                this.onEndUpdateDevGpsDelegate = new EndOperationDelegate(this.OnEndUpdateDevGps);
            }
            if ((this.onUpdateDevGpsCompletedDelegate == null)) {
                this.onUpdateDevGpsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateDevGpsCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDevGpsDelegate, new object[] {
                        model}, this.onEndUpdateDevGpsDelegate, this.onUpdateDevGpsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginDeleteDevGpsByID(string ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteDevGpsByID(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndDeleteDevGpsByID(System.IAsyncResult result) {
            return base.Channel.EndDeleteDevGpsByID(result);
        }
        
        private System.IAsyncResult OnBeginDeleteDevGpsByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID = ((string)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginDeleteDevGpsByID(ID, callback, asyncState);
        }
        
        private object[] OnEndDeleteDevGpsByID(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndDeleteDevGpsByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteDevGpsByIDCompleted(object state) {
            if ((this.DeleteDevGpsByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteDevGpsByIDCompleted(this, new DeleteDevGpsByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteDevGpsByIDAsync(string ID) {
            this.DeleteDevGpsByIDAsync(ID, null);
        }
        
        public void DeleteDevGpsByIDAsync(string ID, object userState) {
            if ((this.onBeginDeleteDevGpsByIDDelegate == null)) {
                this.onBeginDeleteDevGpsByIDDelegate = new BeginOperationDelegate(this.OnBeginDeleteDevGpsByID);
            }
            if ((this.onEndDeleteDevGpsByIDDelegate == null)) {
                this.onEndDeleteDevGpsByIDDelegate = new EndOperationDelegate(this.OnEndDeleteDevGpsByID);
            }
            if ((this.onDeleteDevGpsByIDCompletedDelegate == null)) {
                this.onDeleteDevGpsByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteDevGpsByIDCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDevGpsByIDDelegate, new object[] {
                        ID}, this.onEndDeleteDevGpsByIDDelegate, this.onDeleteDevGpsByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginGetDevGps(string ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDevGps(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndGetDevGps(System.IAsyncResult result) {
            return base.Channel.EndGetDevGps(result);
        }
        
        private System.IAsyncResult OnBeginGetDevGps(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID = ((string)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginGetDevGps(ID, callback, asyncState);
        }
        
        private object[] OnEndGetDevGps(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndGetDevGps(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDevGpsCompleted(object state) {
            if ((this.GetDevGpsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDevGpsCompleted(this, new GetDevGpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDevGpsAsync(string ID) {
            this.GetDevGpsAsync(ID, null);
        }
        
        public void GetDevGpsAsync(string ID, object userState) {
            if ((this.onBeginGetDevGpsDelegate == null)) {
                this.onBeginGetDevGpsDelegate = new BeginOperationDelegate(this.OnBeginGetDevGps);
            }
            if ((this.onEndGetDevGpsDelegate == null)) {
                this.onEndGetDevGpsDelegate = new EndOperationDelegate(this.OnEndGetDevGps);
            }
            if ((this.onGetDevGpsCompletedDelegate == null)) {
                this.onGetDevGpsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDevGpsCompleted);
            }
            base.InvokeAsync(this.onBeginGetDevGpsDelegate, new object[] {
                        ID}, this.onEndGetDevGpsDelegate, this.onGetDevGpsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginGetDevGpsBySN(string ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDevGpsBySN(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndGetDevGpsBySN(System.IAsyncResult result) {
            return base.Channel.EndGetDevGpsBySN(result);
        }
        
        private System.IAsyncResult OnBeginGetDevGpsBySN(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID = ((string)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginGetDevGpsBySN(ID, callback, asyncState);
        }
        
        private object[] OnEndGetDevGpsBySN(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndGetDevGpsBySN(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDevGpsBySNCompleted(object state) {
            if ((this.GetDevGpsBySNCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDevGpsBySNCompleted(this, new GetDevGpsBySNCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDevGpsBySNAsync(string ID) {
            this.GetDevGpsBySNAsync(ID, null);
        }
        
        public void GetDevGpsBySNAsync(string ID, object userState) {
            if ((this.onBeginGetDevGpsBySNDelegate == null)) {
                this.onBeginGetDevGpsBySNDelegate = new BeginOperationDelegate(this.OnBeginGetDevGpsBySN);
            }
            if ((this.onEndGetDevGpsBySNDelegate == null)) {
                this.onEndGetDevGpsBySNDelegate = new EndOperationDelegate(this.OnEndGetDevGpsBySN);
            }
            if ((this.onGetDevGpsBySNCompletedDelegate == null)) {
                this.onGetDevGpsBySNCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDevGpsBySNCompleted);
            }
            base.InvokeAsync(this.onBeginGetDevGpsBySNDelegate, new object[] {
                        ID}, this.onEndGetDevGpsBySNDelegate, this.onGetDevGpsBySNCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginGetDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDevGpsList(page, clientID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndGetDevGpsList(System.IAsyncResult result) {
            return base.Channel.EndGetDevGpsList(result);
        }
        
        private System.IAsyncResult OnBeginGetDevGpsList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page = ((Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo)(inValues[0]));
            string clientID = ((string)(inValues[1]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginGetDevGpsList(page, clientID, callback, asyncState);
        }
        
        private object[] OnEndGetDevGpsList(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndGetDevGpsList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDevGpsListCompleted(object state) {
            if ((this.GetDevGpsListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDevGpsListCompleted(this, new GetDevGpsListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDevGpsListAsync(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID) {
            this.GetDevGpsListAsync(page, clientID, null);
        }
        
        public void GetDevGpsListAsync(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, object userState) {
            if ((this.onBeginGetDevGpsListDelegate == null)) {
                this.onBeginGetDevGpsListDelegate = new BeginOperationDelegate(this.OnBeginGetDevGpsList);
            }
            if ((this.onEndGetDevGpsListDelegate == null)) {
                this.onEndGetDevGpsListDelegate = new EndOperationDelegate(this.OnEndGetDevGpsList);
            }
            if ((this.onGetDevGpsListCompletedDelegate == null)) {
                this.onGetDevGpsListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDevGpsListCompleted);
            }
            base.InvokeAsync(this.onBeginGetDevGpsListDelegate, new object[] {
                        page,
                        clientID}, this.onEndGetDevGpsListDelegate, this.onGetDevGpsListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginGetByNameDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, string name, string vehicleID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByNameDevGpsList(page, clientID, name, vehicleID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndGetByNameDevGpsList(System.IAsyncResult result) {
            return base.Channel.EndGetByNameDevGpsList(result);
        }
        
        private System.IAsyncResult OnBeginGetByNameDevGpsList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page = ((Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo)(inValues[0]));
            string clientID = ((string)(inValues[1]));
            string name = ((string)(inValues[2]));
            string vehicleID = ((string)(inValues[3]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginGetByNameDevGpsList(page, clientID, name, vehicleID, callback, asyncState);
        }
        
        private object[] OnEndGetByNameDevGpsList(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndGetByNameDevGpsList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByNameDevGpsListCompleted(object state) {
            if ((this.GetByNameDevGpsListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByNameDevGpsListCompleted(this, new GetByNameDevGpsListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByNameDevGpsListAsync(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, string name, string vehicleID) {
            this.GetByNameDevGpsListAsync(page, clientID, name, vehicleID, null);
        }
        
        public void GetByNameDevGpsListAsync(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, string name, string vehicleID, object userState) {
            if ((this.onBeginGetByNameDevGpsListDelegate == null)) {
                this.onBeginGetByNameDevGpsListDelegate = new BeginOperationDelegate(this.OnBeginGetByNameDevGpsList);
            }
            if ((this.onEndGetByNameDevGpsListDelegate == null)) {
                this.onEndGetByNameDevGpsListDelegate = new EndOperationDelegate(this.OnEndGetByNameDevGpsList);
            }
            if ((this.onGetByNameDevGpsListCompletedDelegate == null)) {
                this.onGetByNameDevGpsListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByNameDevGpsListCompleted);
            }
            base.InvokeAsync(this.onBeginGetByNameDevGpsListDelegate, new object[] {
                        page,
                        clientID,
                        name,
                        vehicleID}, this.onEndGetByNameDevGpsListDelegate, this.onGetByNameDevGpsListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginBatchAddDevGps(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBatchAddDevGps(devGpsBatchList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndBatchAddDevGps(System.IAsyncResult result) {
            return base.Channel.EndBatchAddDevGps(result);
        }
        
        private System.IAsyncResult OnBeginBatchAddDevGps(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList = ((System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps>)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginBatchAddDevGps(devGpsBatchList, callback, asyncState);
        }
        
        private object[] OnEndBatchAddDevGps(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndBatchAddDevGps(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBatchAddDevGpsCompleted(object state) {
            if ((this.BatchAddDevGpsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BatchAddDevGpsCompleted(this, new BatchAddDevGpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BatchAddDevGpsAsync(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList) {
            this.BatchAddDevGpsAsync(devGpsBatchList, null);
        }
        
        public void BatchAddDevGpsAsync(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, object userState) {
            if ((this.onBeginBatchAddDevGpsDelegate == null)) {
                this.onBeginBatchAddDevGpsDelegate = new BeginOperationDelegate(this.OnBeginBatchAddDevGps);
            }
            if ((this.onEndBatchAddDevGpsDelegate == null)) {
                this.onEndBatchAddDevGpsDelegate = new EndOperationDelegate(this.OnEndBatchAddDevGps);
            }
            if ((this.onBatchAddDevGpsCompletedDelegate == null)) {
                this.onBatchAddDevGpsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBatchAddDevGpsCompleted);
            }
            base.InvokeAsync(this.onBeginBatchAddDevGpsDelegate, new object[] {
                        devGpsBatchList}, this.onEndBatchAddDevGpsDelegate, this.onBatchAddDevGpsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.BeginCheckDevGpsExist(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckDevGpsExist(devGpsBatchList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService.EndCheckDevGpsExist(System.IAsyncResult result) {
            return base.Channel.EndCheckDevGpsExist(result);
        }
        
        private System.IAsyncResult OnBeginCheckDevGpsExist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList = ((System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps>)(inValues[0]));
            return ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).BeginCheckDevGpsExist(devGpsBatchList, callback, asyncState);
        }
        
        private object[] OnEndCheckDevGpsExist(System.IAsyncResult result) {
            Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 retVal = ((Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService)(this)).EndCheckDevGpsExist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckDevGpsExistCompleted(object state) {
            if ((this.CheckDevGpsExistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckDevGpsExistCompleted(this, new CheckDevGpsExistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckDevGpsExistAsync(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList) {
            this.CheckDevGpsExistAsync(devGpsBatchList, null);
        }
        
        public void CheckDevGpsExistAsync(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, object userState) {
            if ((this.onBeginCheckDevGpsExistDelegate == null)) {
                this.onBeginCheckDevGpsExistDelegate = new BeginOperationDelegate(this.OnBeginCheckDevGpsExist);
            }
            if ((this.onEndCheckDevGpsExistDelegate == null)) {
                this.onEndCheckDevGpsExistDelegate = new EndOperationDelegate(this.OnEndCheckDevGpsExist);
            }
            if ((this.onCheckDevGpsExistCompletedDelegate == null)) {
                this.onCheckDevGpsExistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckDevGpsExistCompleted);
            }
            base.InvokeAsync(this.onBeginCheckDevGpsExistDelegate, new object[] {
                        devGpsBatchList}, this.onEndCheckDevGpsExistDelegate, this.onCheckDevGpsExistCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService CreateChannel() {
            return new DevGpsServiceClientChannel(this);
        }
        
        private class DevGpsServiceClientChannel : ChannelBase<Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService>, Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService {
            
            public DevGpsServiceClientChannel(System.ServiceModel.ClientBase<Gsafety.PTMS.ServiceReference.DevGpsService.IDevGpsService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInsertDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = model;
                System.IAsyncResult _result = base.BeginInvoke("InsertDevGps", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndInsertDevGps(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(base.EndInvoke("InsertDevGps", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateDevGps(Gsafety.PTMS.ServiceReference.DevGpsService.DevGps model, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = model;
                System.IAsyncResult _result = base.BeginInvoke("UpdateDevGps", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndUpdateDevGps(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(base.EndInvoke("UpdateDevGps", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteDevGpsByID(string ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("DeleteDevGpsByID", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndDeleteDevGpsByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(base.EndInvoke("DeleteDevGpsByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDevGps(string ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("GetDevGps", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 EndGetDevGps(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5)(base.EndInvoke("GetDevGps", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDevGpsBySN(string ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("GetDevGpsBySN", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 EndGetDevGpsBySN(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfDevGpsi7Zg_POJ5)(base.EndInvoke("GetDevGpsBySN", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = page;
                _args[1] = clientID;
                System.IAsyncResult _result = base.BeginInvoke("GetDevGpsList", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndGetDevGpsList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(base.EndInvoke("GetDevGpsList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByNameDevGpsList(Gsafety.PTMS.ServiceReference.DevGpsService.PagingInfo page, string clientID, string name, string vehicleID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = page;
                _args[1] = clientID;
                _args[2] = name;
                _args[3] = vehicleID;
                System.IAsyncResult _result = base.BeginInvoke("GetByNameDevGpsList", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndGetByNameDevGpsList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(base.EndInvoke("GetByNameDevGpsList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBatchAddDevGps(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = devGpsBatchList;
                System.IAsyncResult _result = base.BeginInvoke("BatchAddDevGps", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean EndBatchAddDevGps(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.SingleMessageOfboolean)(base.EndInvoke("BatchAddDevGps", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCheckDevGpsExist(System.Collections.ObjectModel.ObservableCollection<Gsafety.PTMS.ServiceReference.DevGpsService.DevGps> devGpsBatchList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = devGpsBatchList;
                System.IAsyncResult _result = base.BeginInvoke("CheckDevGpsExist", _args, callback, asyncState);
                return _result;
            }
            
            public Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 EndCheckDevGpsExist(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5 _result = ((Gsafety.PTMS.ServiceReference.DevGpsService.MultiMessageOfDevGpsi7Zg_POJ5)(base.EndInvoke("CheckDevGpsExist", _args, result)));
                return _result;
            }
        }
    }
}
