//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALM_ALARM_DISPOSE
    {
        public string ID { get; set; }
        public string ALARM_ID { get; set; }
        public Nullable<int> ALARM_FLAG { get; set; }
        public string CONTENT { get; set; }
        public string DISPOSE_STAFF { get; set; }
        public Nullable<System.DateTime> DISPOSE_TIME { get; set; }
    }
}
