//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALT_BUSINESS_ALERT
    {
        public string ID { get; set; }
        public string CLIENT_ID { get; set; }
        public string SUITE_INFO_ID { get; set; }
        public string MDVR_CORE_SN { get; set; }
        public string VEHICLE_ID { get; set; }
        public Nullable<int> SUITE_STATUS { get; set; }
        public string GPS_VALID { get; set; }
        public Nullable<int> ALERT_TYPE { get; set; }
        public Nullable<System.DateTime> ALERT_TIME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public Nullable<System.DateTime> GPS_TIME { get; set; }
        public string SPEED { get; set; }
        public string DIRECTION { get; set; }
        public string RULE_ID { get; set; }
        public string ADDITIONAL_INFO { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    }
}
