//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSC_ORDER_CLIENT
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime BEGIN_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT { get; set; }
        public int TANSFER_MODE { get; set; }
        public int STATUS { get; set; }
        public int USER_COUNT { get; set; }
        public int DEVICE_COUNT { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int VERSION { get; set; }
    }
}
