//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_DATA
    {
        public string ID { get; set; }
        public string CLIENT_ID { get; set; }
        public string USER_NAME { get; set; }
        public string MSG_ID { get; set; }
        public string USER_TYPE { get; set; }
        public int CONTENTTYPE { get; set; }
        public string USER_DEPT { get; set; }
        public string MDVR_CORE_SN { get; set; }
        public Nullable<System.DateTime> ACCESS_TIME { get; set; }
        public string VEHICLE_ID { get; set; }
        public string CHANNEL { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string FILE_NAME { get; set; }
        public string EXTENED1 { get; set; }
        public string EXTENED2 { get; set; }
        public string EXTENED3 { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string ORGANIZATION_ID { get; set; }
    }
}
