//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDI_PHOTOGRAPH
    {
        public string ID { get; set; }
        public string CLIENT_ID { get; set; }
        public int DEVICE_TYPE { get; set; }
        public string DEVICE_SN { get; set; }
        public int CHANNEL_ID { get; set; }
        public string IMG_URL { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int IMGSIZE { get; set; }
        public int STATUS { get; set; }
        public string NOTE { get; set; }
        public string MINIIMG_URL { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
    }
}
