//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTN_INSTALLATION_AUDIT
    {
        public string INSTALL_ID { get; set; }
        public string ALARM_ID { get; set; }
        public Nullable<int> GPS_CHECK { get; set; }
        public Nullable<int> ALARM_CHECK { get; set; }
        public Nullable<int> AUDIT_FLAG { get; set; }
        public Nullable<System.DateTime> APPROVE_TIME { get; set; }
        public string APPROVER { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> VIDEO_CHECK { get; set; }
    }
}
