//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsafety.PTMS.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUN_VEHICLE_LOCATION
    {
        public string ID { get; set; }
        public string CLIENT_ID { get; set; }
        public string VEHICLE_ID { get; set; }
        public int SOURCE { get; set; }
        public string GPS_VALID { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string SPEED { get; set; }
        public string DIRECTION { get; set; }
        public Nullable<System.DateTime> GPS_TIME { get; set; }
        public string DISTRICT_CODE { get; set; }
        public int ALARM_FLAG { get; set; }
        public int STATUS_FLAG { get; set; }
        public Nullable<int> SOURCE_MODE { get; set; }
        public string DEVICE_ID { get; set; }
    }
}
