
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class ALM_911_DISPOSE
{

    public string ALARM_ID { get; set; }

    public Nullable<int> FORWARDED_FLAG { get; set; }

    public Nullable<int> ALARM_FLAG { get; set; }

    public Nullable<System.DateTime> DISPOSE_TIME { get; set; }

    public string DISPOSE_STAFF { get; set; }

    public string TRANSFER_CENTER { get; set; }

    public string INCIDENT_ID { get; set; }

    public string FORWARD_DEST { get; set; }

    public Nullable<System.DateTime> FORWARD_TIME { get; set; }

    public string ALARM_ADDRESS { get; set; }

    public string CONTENT { get; set; }

    public string INCIDENT_TYPE { get; set; }

    public string APPREAL_STAFF { get; set; }

    public string DISPOSE_CONTENT { get; set; }

    public System.DateTime CREATE_TIME { get; set; }

    public string ID { get; set; }

    public Nullable<int> TRANSFER_MODE { get; set; }

    public Nullable<int> IS_TRANSFER { get; set; }

    public Nullable<System.DateTime> APPEAL_TIME { get; set; }

    public Nullable<int> INCIDENT_LEVEL { get; set; }

}

}
