
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class BSC_GEO_POI
{

    public int ID { get; set; }

    public string NAME { get; set; }

    public double LONGITUDE { get; set; }

    public double LATIDUE { get; set; }

    public string ADDRESS { get; set; }

    public string CONTRY { get; set; }

    public int PROPERTY { get; set; }

    public int DATASTATUS { get; set; }

}

}
