
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class CFG_APP_CONFIG
{

    public string ID { get; set; }

    public string SECTION_DESC { get; set; }

    public string SECTION_NAME { get; set; }

    public string SECTION_TYPE { get; set; }

    public string SECTION_UNIT { get; set; }

    public string SECTION_VALUE { get; set; }

    public string CLIENT_ID { get; set; }

}

}
