
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class MTN_MAINTAIN_APPLICATION
{

    public string ID { get; set; }

    public string CLIENT_ID { get; set; }

    public string APPLICANT { get; set; }

    public string SETUP_STATION { get; set; }

    public int STATUS { get; set; }

    public string NOTE { get; set; }

    public string WORKER { get; set; }

    public string WORKER_PHONE { get; set; }

    public Nullable<System.DateTime> SCHEDULE_DATE { get; set; }

    public string CREATOR { get; set; }

    public System.DateTime CREATE_TIME { get; set; }

    public string PROBLEM { get; set; }

    public string CONTACT { get; set; }

    public string VEHCILE_ID { get; set; }

}

}
