
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class RUN_MONITOR_GROUP
{

    public string ID { get; set; }

    public string AD_USER { get; set; }

    public string GROUP_NAME { get; set; }

    public int GROUP_TYPE { get; set; }

    public int IS_DEFAULT { get; set; }

    public Nullable<int> GROUP_INDEX { get; set; }

    public string NOTE { get; set; }

}

}
