
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gsafety.PTMS.DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class RUN_SUITE_WORKING
{

    public string SUITE_INFO_ID { get; set; }

    public string CLIENT_ID { get; set; }

    public string VEHICLE_ID { get; set; }

    public string MDVR_CORE_SN { get; set; }

    public Nullable<int> STATUS { get; set; }

    public Nullable<System.DateTime> SWITCH_TIME { get; set; }

    public Nullable<int> ONLINE_FLAG { get; set; }

    public Nullable<System.DateTime> FAULT_TIME { get; set; }

    public string ABNORMAL_CAUSE { get; set; }

    public string ORGANIZATION_ID { get; set; }

}

}
